language: go

go:
- 1.11.x

git:
  depth: 3

install: true

dist: trusty
sudo: false

os:
#- linux
- windows

notifications:
  email: false

before_install:
- go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

script:
- env GO111MODULE=on go generate
- env GO111MODULE=on go build
- env GO111MODULE=on go test -v -race ./...

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: $push_secure_token
  file: cord.stool.exe
  on:
    tags: true
    repo: ProtocolONE/cord.stool
