language: go

go:
- 1.11.x

git:
  depth: 3

#install: true

dist: trusty
sudo: false

os:
- windows

notifications:
  email: false

#before_install:
#- env GO111MODULE=on go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
# - env GO111MODULE=on go get -u

install:
- travis_wait env GO111MODULE=on go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
- travis_wait env GO111MODULE=on go get -u

script:
#- travis_wait env GO111MODULE=on go get -u
#- env GO111MODULE=on vtag=$TRAVIS_TAG v1=`go run tag/tag.go $vtag 1` && v2=`go run tag/tag.go $vtag 2` && v3=`go run tag/tag.go $vtag 3`&& goversioninfo -ver-major=$v1 -ver-minor=$v2 -ver-patch=$v3 -ver-build=$TRAVIS_BUILD_NUMBER -file-version="$v1.$v2.$v3" -product-version="$v1.$v2.$v3.`git log -1 --pretty=format:%h`" -product-ver-major=$v1 -product-ver-minor=$v2 -product-ver-patch=$v3 -product-ver-build=$TRAVIS_BUILD_NUMBER
- travis_wait env GO111MODULE=on go build
- travis_wait env GO111MODULE=on go test -v -race ./...

deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: $push_secure_token
  file: cord.stool.exe
  on:
    tags: true
    repo: ProtocolONE/cord.stool
